#!/usr/bin/env python3
"""Constants for the Program Go Here"""

# URL Constants

# System Related Constants
BACKGROUND_AUDIO_DIRECTORY = "./Background-Audio"
GENERATED_AUDIO_DIRECTORY = "./Generated-Audio"
BACKGROUND_VIDEO_DIRECTORY = "./Background-Video"
GENERATED_VIDEO_DIRECTORY = "./Generated-Video"
FULL_DIRECTORY_LIST = [
    BACKGROUND_AUDIO_DIRECTORY,
    GENERATED_AUDIO_DIRECTORY,
    BACKGROUND_VIDEO_DIRECTORY,
    GENERATED_VIDEO_DIRECTORY,
]
SEED_DIRECTORY_LIST = [BACKGROUND_AUDIO_DIRECTORY, BACKGROUND_VIDEO_DIRECTORY]

VIDEOS_FIXED = False

# Program Related Constants
WORD_LIMIT = 450
